function [ output_args ] = LF_create_onsets
%% LF_create onsets Extracts the onset times for fMRI analyses
%   This function reads in the Timing stimulus files and Trial events files 
% that were generated by LF_formatdata.m. Then, we extract out the
% block-related onsets and duration for the duration-modulated block
% regressor in AFNI, as well as the event-related onsets for each trial,
% separated by monetary reward level ($,$$,$$$$).
% 
% INPUT: We need to update the subjects and the runkey, which tells us the
% order in which the liquids were delivered during the actual experiment.

%% Runs the LF_formatdata function to make sure that the files are up to date 
% Also reads in the formatted/trimmed stimuli data
% LF_formatdata
clear all; 

% Tstim = readtable('/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/Trimmed/stim_present_data.txt', ...
%     'Delimiter','\t', 'ReadVariableNames',true);
% Trial = readtable('/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/Trimmed/subject_data.txt', ...
%     'Delimiter','\t', 'ReadVariableNames',true);

Tstim = readtable('/Users/debbieyee/Box Sync/Aging Motivation (SRNDNA)/Data/Trimmed/stim_present_data.txt', ...
    'Delimiter','\t','ReadVariableNames',true);
Trial = readtable('/Users/debbieyee/Box Sync/Aging Motivation (SRNDNA)/Data/Trimmed/subject_data.txt', ...
    'Delimiter','\t', 'ReadVariableNames',true);

%% Extracting the event onsets for block & event-related designs: Subjects 1-17
subjects = [2:4 6:17];

% Runkey of the liquid types based on the behavioral checklist.
% NOTE: the runs start at 8, not 1.
%[base1 juice juice neutral neutral saltwater saltwater]
runkey = [8 9 10 13 14 11 12;    % s02
          8 11 12 9 10 13 14;    % s03
          8 13 14 9 10 11 12;    % s04
          8 13 14 11 12 9 10;    % s06
          8 9 10 11 12 13 14;    % s07
          8 9 10 13 14 11 12;    % s08
          8 11 12 9 10 13 14;    % s09
          8 13 14 9 10 11 12;    % s10
          8 11 12 13 14 9 10;    % s11
          8 13 14 11 12 9 10;    % s12
          8 9 10 11 12 13 14;    % s13
          8 9 10 13 14 11 12;    % s14
          8 11 12 9 10 13 14;    % s15
          8 13 14 9 10 11 12;    % s16
          8 11 12 13 14 9 10];   % s17
      
% extract timing onsets for each run, for each subject      
for s = 1:length(subjects)
    
    % baseline 1 onsets (1 run)
    ix = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,1) & strcmp(Tstim.runType,'baseline') & (Tstim.trial==1 | Tstim.trial==17 | Tstim.trial==33) & strcmp(Tstim.stim_present,'trialstart'))';
    onsets_base = table2array(Tstim(ix,7))';
    % duration
    ix_d = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,1) & strcmp(Tstim.runType,'baseline') & (Tstim.trial==16 | Tstim.trial==32 | Tstim.trial==48) & strcmp(Tstim.stim_present,'ITI'))';
    onsets_dur_base = table2array(Tstim(ix_d,7))' - onsets_base;
    
    %[num2str(onsets_base(1)),':',num2str(onsets_dur_base(1))]
    %test={[num2str(onsets_base(1)),':',num2str(onsets_dur_base(1))],[num2str(onsets_base(2)),':',num2str(onsets_dur_base(2))],[num2str(onsets_base(3)),':',num2str(onsets_dur_base(3))]}

    % juice onsets (2 runs)
    ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,2) & strcmp(Tstim.runType,'incentive') & (Tstim.trial==1 | Tstim.trial==17 | Tstim.trial==33) & strcmp(Tstim.stim_present,'trialstart'));
    ix2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,3) & strcmp(Tstim.runType,'incentive') & (Tstim.trial==1 | Tstim.trial==17 | Tstim.trial==33) & strcmp(Tstim.stim_present,'trialstart'));    
    onsets_juice = [table2array(Tstim(ix1,7))'; table2array(Tstim(ix2,7))'];
    % duration
    ix_d1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,2) & strcmp(Tstim.runType,'incentive') & (Tstim.trial==16 | Tstim.trial==32 | Tstim.trial==48) & strcmp(Tstim.stim_present,'ITI'));
    ix_d2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,3) & strcmp(Tstim.runType,'incentive') & (Tstim.trial==16 | Tstim.trial==32 | Tstim.trial==48) & strcmp(Tstim.stim_present,'ITI'));    
    onsets_dur_juice = [table2array(Tstim(ix_d1,7))'; table2array(Tstim(ix_d2,7))'] - onsets_juice;   
        
    % neutral onsets (2 runs)
    ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,4) & strcmp(Tstim.runType,'incentive') & (Tstim.trial==1 | Tstim.trial==17 | Tstim.trial==33) & strcmp(Tstim.stim_present,'trialstart'));
    ix2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,5) & strcmp(Tstim.runType,'incentive') & (Tstim.trial==1 | Tstim.trial==17 | Tstim.trial==33) & strcmp(Tstim.stim_present,'trialstart'));    
    onsets_neut = [table2array(Tstim(ix1,7))'; table2array(Tstim(ix2,7))'];
    % duration
    ix_d1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,4) & strcmp(Tstim.runType,'incentive') & (Tstim.trial==16 | Tstim.trial==32 | Tstim.trial==48) & strcmp(Tstim.stim_present,'ITI'));
    ix_d2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,5) & strcmp(Tstim.runType,'incentive') & (Tstim.trial==16 | Tstim.trial==32 | Tstim.trial==48) & strcmp(Tstim.stim_present,'ITI'));    
    onsets_dur_neut = [table2array(Tstim(ix_d1,7))'; table2array(Tstim(ix_d2,7))'] - onsets_neut;       
    
    % saltwater onsets (2 runs)
    ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,6) & strcmp(Tstim.runType,'incentive') & (Tstim.trial==1 | Tstim.trial==17 | Tstim.trial==33) & strcmp(Tstim.stim_present,'trialstart'));
    ix2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,7) & strcmp(Tstim.runType,'incentive') & (Tstim.trial==1 | Tstim.trial==17 | Tstim.trial==33) & strcmp(Tstim.stim_present,'trialstart'));   
    onsets_salt = [table2array(Tstim(ix1,7))'; table2array(Tstim(ix2,7))'];    
    % duration
    ix_d1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,6) & strcmp(Tstim.runType,'incentive') & (Tstim.trial==16 | Tstim.trial==32 | Tstim.trial==48) & strcmp(Tstim.stim_present,'ITI'));
    ix_d2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,7) & strcmp(Tstim.runType,'incentive') & (Tstim.trial==16 | Tstim.trial==32 | Tstim.trial==48) & strcmp(Tstim.stim_present,'ITI'));    
    onsets_dur_salt = [table2array(Tstim(ix_d1,7))'; table2array(Tstim(ix_d2,7))'] - onsets_salt;       
    
    % save text files for base onsets
    if subjects(s) < 10
        % onsets
        fname_base = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block/s00',num2str(subjects(s)),'_base_block.txt'];
        fname_juice = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block/s00',num2str(subjects(s)),'_juice_block.txt'];
        fname_neut = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block/s00',num2str(subjects(s)),'_neut_block.txt'];
        fname_salt = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block/s00',num2str(subjects(s)),'_salt_block.txt'];
        % duration
        fname_dur_base = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block_duration/s00',num2str(subjects(s)),'_base_dur_block.txt'];
        fname_dur_juice = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block_duration/s00',num2str(subjects(s)),'_juice_dur_block.txt'];
        fname_dur_neut = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block_duration/s00',num2str(subjects(s)),'_neut_dur_block.txt'];
        fname_dur_salt = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block_duration/s00',num2str(subjects(s)),'_salt_dur_block.txt']; 
        % duration modulated onsets
        fname_dm_base = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/dmblock/s00',num2str(subjects(s)),'_dmBLOCK_BASE.txt'];
        fname_dm_juice = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/dmblock/s00',num2str(subjects(s)),'_dmBLOCK_JUICE.txt'];
        fname_dm_neut = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/dmblock/s00',num2str(subjects(s)),'_dmBLOCK_NEUT.txt'];
        fname_dm_salt = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/dmblock/s00',num2str(subjects(s)),'_dmBLOCK_SALT.txt']; 
    else
        % onsets
        fname_base = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block/s0',num2str(subjects(s)),'_base_block.txt'];
        fname_juice = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block/s0',num2str(subjects(s)),'_juice_block.txt'];
        fname_neut = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block/s0',num2str(subjects(s)),'_neut_block.txt'];
        fname_salt = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block/s0',num2str(subjects(s)),'_salt_block.txt'];
        % duration
        fname_dur_base = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block_duration/s0',num2str(subjects(s)),'_base_dur_block.txt'];
        fname_dur_juice = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block_duration/s0',num2str(subjects(s)),'_juice_dur_block.txt'];
        fname_dur_neut = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block_duration/s0',num2str(subjects(s)),'_neut_dur_block.txt'];
        fname_dur_salt = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/block_duration/s0',num2str(subjects(s)),'_salt_dur_block.txt'];       
        % duration
        fname_dm_base = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/dmblock/s0',num2str(subjects(s)),'_dmBLOCK_BASE.txt'];
        fname_dm_juice = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/dmblock/s0',num2str(subjects(s)),'_dmBLOCK_JUICE.txt'];
        fname_dm_neut = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/dmblock/s0',num2str(subjects(s)),'_dmBLOCK_NEUT.txt'];
        fname_dm_salt = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/dmblock/s0',num2str(subjects(s)),'_dmBLOCK_SALT.txt']; 
    end
    
    % writing the onsets
    dlmwrite(fname_base,onsets_base,'delimiter','\t')
    dlmwrite(fname_juice,onsets_juice,'delimiter','\t')
    dlmwrite(fname_neut,onsets_neut,'delimiter','\t')
    dlmwrite(fname_salt,onsets_salt,'delimiter','\t')
    
    % writing the duration
    dlmwrite(fname_dur_base,onsets_dur_base,'delimiter','\t')
    dlmwrite(fname_dur_juice,onsets_dur_juice,'delimiter','\t')
    dlmwrite(fname_dur_neut,onsets_dur_neut,'delimiter','\t')
    dlmwrite(fname_dur_salt,onsets_dur_salt,'delimiter','\t')    
    
    
    % combining the onsets and duration, and writing to a file
    % NOTE: after these are written to text file,s the b1, b2, and b3 must
    % be removed from the columns of the text files.
    % baseline
    onsets_dm_base = {strcat(num2str(onsets_base(1)),':',num2str(onsets_dur_base(1)),' ') ...
                      strcat(num2str(onsets_base(2)),':',num2str(onsets_dur_base(2)),' ') ...
                      strcat(num2str(onsets_base(3)),':',num2str(onsets_dur_base(3)),' ')};
    dm.base=cell2table(onsets_dm_base,'VariableNames',{'b1','b2','b3'});
    writetable(dm.base,fname_dm_base, 'delimiter','\t')
    
    % juice
    onsets_dm_juice = {strcat(num2str(onsets_juice(1,1)),':',num2str(onsets_dur_juice(1,1)),' ') ...
                      strcat(num2str(onsets_juice(1,2)),':',num2str(onsets_dur_juice(1,2)),' ') ...
                      strcat(num2str(onsets_juice(1,3)),':',num2str(onsets_dur_juice(1,3)),' ');
                      strcat(num2str(onsets_juice(2,1)),':',num2str(onsets_dur_juice(2,1)),' ') ...
                      strcat(num2str(onsets_juice(2,2)),':',num2str(onsets_dur_juice(2,2)),' ') ...
                      strcat(num2str(onsets_juice(2,3)),':',num2str(onsets_dur_juice(2,3)),' ')};
    dm.juice=cell2table(onsets_dm_juice,'VariableNames',{'b1','b2','b3'});
    writetable(dm.juice,fname_dm_juice, 'delimiter','\t')   
    
    % neutral
    onsets_dm_neut = {strcat(num2str(onsets_neut(1,1)),':',num2str(onsets_dur_neut(1,1)),' ') ...
                      strcat(num2str(onsets_neut(1,2)),':',num2str(onsets_dur_neut(1,2)),' ') ...
                      strcat(num2str(onsets_neut(1,3)),':',num2str(onsets_dur_neut(1,3)),' ');
                      strcat(num2str(onsets_neut(2,1)),':',num2str(onsets_dur_neut(2,1)),' ') ...
                      strcat(num2str(onsets_neut(2,2)),':',num2str(onsets_dur_neut(2,2)),' ') ...
                      strcat(num2str(onsets_neut(2,3)),':',num2str(onsets_dur_neut(2,3)),' ')};
    dm.neut=cell2table(onsets_dm_neut,'VariableNames',{'b1','b2','b3'});
    writetable(dm.neut,fname_dm_neut, 'delimiter','\t')   
    
    % saltwater
    onsets_dm_salt = {strcat(num2str(onsets_salt(1,1)),':',num2str(onsets_dur_salt(1,1)),' ') ...
                      strcat(num2str(onsets_salt(1,2)),':',num2str(onsets_dur_salt(1,2)),' ') ...
                      strcat(num2str(onsets_salt(1,3)),':',num2str(onsets_dur_salt(1,3)),' ');
                      strcat(num2str(onsets_salt(2,1)),':',num2str(onsets_dur_salt(2,1)),' ') ...
                      strcat(num2str(onsets_salt(2,2)),':',num2str(onsets_dur_salt(2,2)),' ') ...
                      strcat(num2str(onsets_salt(2,3)),':',num2str(onsets_dur_salt(2,3)),' ')};
    dm.salt=cell2table(onsets_dm_salt,'VariableNames',{'b1','b2','b3'});
    writetable(dm.salt,fname_dm_salt, 'delimiter','\t')     
    
    
    
%     % event related -- COLLAPSES ACROSS ALL MONETARY VALUES
%    
%     % run 1: baseline
%     ix = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,1) & strcmp(Tstim.runType,'baseline') & (Tstim.trial~=1 & Tstim.trial~=17 & Tstim.trial~=33) & strcmp(Tstim.stim_present,'trialstart'));
%     onsets_base_EV = table2array(Tstim(ix,7))';
%     
%     % run 2 & 3: juice onsets (2 runs)
%     ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,2) & strcmp(Tstim.runType,'incentive') & (Tstim.trial~=1 & Tstim.trial~=17 & Tstim.trial~=33) & strcmp(Tstim.stim_present,'trialstart'));
%     ix2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,3) & strcmp(Tstim.runType,'incentive') & (Tstim.trial~=1 & Tstim.trial~=17 & Tstim.trial~=33) & strcmp(Tstim.stim_present,'trialstart'));    
%     onsets_juice_EV = [table2array(Tstim(ix1,7))'; table2array(Tstim(ix2,7))'];
%     
%     % run 4 & 5: neutral onsets (2 runs):
%     ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,4) & strcmp(Tstim.runType,'incentive') & (Tstim.trial~=1 & Tstim.trial~=17 & Tstim.trial~=33) & strcmp(Tstim.stim_present,'trialstart'));
%     ix2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,5) & strcmp(Tstim.runType,'incentive') & (Tstim.trial~=1 & Tstim.trial~=17 & Tstim.trial~=33) & strcmp(Tstim.stim_present,'trialstart'));    
%     onsets_neut_EV = [table2array(Tstim(ix1,7))'; table2array(Tstim(ix2,7))'];   
%     
%     % run 6 & 7: saltwater onsets (2 runs)
%     ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,6) & strcmp(Tstim.runType,'incentive') & (Tstim.trial~=1 & Tstim.trial~=17 & Tstim.trial~=33) & strcmp(Tstim.stim_present,'trialstart'));
%     ix2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,7) & strcmp(Tstim.runType,'incentive') & (Tstim.trial~=1 & Tstim.trial~=17 & Tstim.trial~=33) & strcmp(Tstim.stim_present,'trialstart'));   
%     onsets_salt_EV = [table2array(Tstim(ix1,7))'; table2array(Tstim(ix2,7))'];       
%     
%     % All event onsets
%     onsets_EV = [onsets_base_EV;onsets_juice_EV;onsets_neut_EV;onsets_salt_EV;];
%     
%     % Event onsets only at first of block
%     onsets_EVstart = [onsets_base;onsets_juice;onsets_neut;onsets_salt];
%     
%     % save text files for event related onsets
%     if subjects(s) < 10
%         % onsets events
%         fname_EV = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related/s0',num2str(subjects(s)),'_EV.txt'];
%         % onsets event start trial of block
%         fname_EVstart = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related/s0',num2str(subjects(s)),'_EVstart.txt'];
%              
%     else
%         % onsets events
%         fname_EV = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related/s',num2str(subjects(s)),'_EV.txt'];
%         % onsets event start trial of block
%         fname_EVstart = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related/s',num2str(subjects(s)),'_EVstart.txt'];
%         
%     end
%     
%     % writing the onsets for the events and the start of block events
%     dlmwrite(fname_EV,onsets_EV,'delimiter','\t')
%     dlmwrite(fname_EVstart,onsets_EVstart,'delimiter','\t')
    
    
    % event related reward 3 -- SEPARATED BY MONETARY VALUES (EV1, EV2, EV4)
    % first trial of each block from the other events.
    % activation of the first event
    % run 8: baseline 
    ix = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,1) & strcmp(Tstim.runType,'baseline') & strcmp(Tstim.stim_present,'trialstart'));
    ix_t=find(Trial.subID==subjects(s) & Trial.runID==runkey(s,1) & strcmp(Trial.runType,'baseline'));
    onsets_base_EV = table2array(horzcat(Tstim(ix,7),Trial(ix_t,18)));
    onsets_base_EV = onsets_base_EV(:,1)';
    %onsets_base_EV_1 = onsets_base_EV(find(onsets_base_EV(:,2)==1),1)';
    %onsets_base_EV_2 = onsets_base_EV(find(onsets_base_EV(:,2)==2),1)';
    %onsets_base_EV_4 = onsets_base_EV(find(onsets_base_EV(:,2)==4),1)';
    
    % run 9: incentive 
    ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==9 & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
    ix1_t=find(Trial.subID==subjects(s) & Trial.runID==9 & strcmp(Trial.runType,'incentive'));
    onsets_run9_EV = table2array(horzcat(Tstim(ix1,7),Trial(ix1_t,18)));
    onsets_run9_EV_1 = onsets_run9_EV(find(onsets_run9_EV(:,2)==1),1)';
    onsets_run9_EV_2 = onsets_run9_EV(find(onsets_run9_EV(:,2)==2),1)';
    onsets_run9_EV_4 = onsets_run9_EV(find(onsets_run9_EV(:,2)==4),1)';
    
    % run 10: incentive
    ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==10 & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
    ix1_t=find(Trial.subID==subjects(s) & Trial.runID==10 & strcmp(Trial.runType,'incentive'));
    onsets_run10_EV = table2array(horzcat(Tstim(ix1,7),Trial(ix1_t,18)));
    onsets_run10_EV_1 = onsets_run10_EV(find(onsets_run10_EV(:,2)==1),1)';
    onsets_run10_EV_2 = onsets_run10_EV(find(onsets_run10_EV(:,2)==2),1)';
    onsets_run10_EV_4 = onsets_run10_EV(find(onsets_run10_EV(:,2)==4),1)';
    
    % run 11: incentive
    ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==11 & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
    ix1_t=find(Trial.subID==subjects(s) & Trial.runID==11 & strcmp(Trial.runType,'incentive'));
    onsets_run11_EV = table2array(horzcat(Tstim(ix1,7),Trial(ix1_t,18)));
    onsets_run11_EV_1 = onsets_run11_EV(find(onsets_run11_EV(:,2)==1),1)';
    onsets_run11_EV_2 = onsets_run11_EV(find(onsets_run11_EV(:,2)==2),1)';
    onsets_run11_EV_4 = onsets_run11_EV(find(onsets_run11_EV(:,2)==4),1)';
    
    % run 12: incentive
    ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==12 & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
    ix1_t=find(Trial.subID==subjects(s) & Trial.runID==12 & strcmp(Trial.runType,'incentive'));
    onsets_run12_EV = table2array(horzcat(Tstim(ix1,7),Trial(ix1_t,18)));
    onsets_run12_EV_1 = onsets_run12_EV(find(onsets_run12_EV(:,2)==1),1)';
    onsets_run12_EV_2 = onsets_run12_EV(find(onsets_run12_EV(:,2)==2),1)';
    onsets_run12_EV_4 = onsets_run12_EV(find(onsets_run12_EV(:,2)==4),1)';    
    if subjects(s)==3
        onsets_run12_EV_1 = [onsets_run12_EV_1,repmat(NaN,1,16-length(onsets_run12_EV_1))];
        onsets_run12_EV_2 = [onsets_run12_EV_2,repmat(NaN,1,16-length(onsets_run12_EV_2))];
        onsets_run12_EV_4 = [onsets_run12_EV_4,repmat(NaN,1,16-length(onsets_run12_EV_4))];
    end   
    
    % run 13 incentive
    ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==13 & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
    ix1_t=find(Trial.subID==subjects(s) & Trial.runID==13 & strcmp(Trial.runType,'incentive'));
    onsets_run13_EV = table2array(horzcat(Tstim(ix1,7),Trial(ix1_t,18)));
    onsets_run13_EV_1 = onsets_run13_EV(find(onsets_run13_EV(:,2)==1),1)';
    onsets_run13_EV_2 = onsets_run13_EV(find(onsets_run13_EV(:,2)==2),1)';
    onsets_run13_EV_4 = onsets_run13_EV(find(onsets_run13_EV(:,2)==4),1)';    
    
    % run 14: incentive
    ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==14 & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
    ix1_t=find(Trial.subID==subjects(s) & Trial.runID==14 & strcmp(Trial.runType,'incentive'));
    onsets_run14_EV = table2array(horzcat(Tstim(ix1,7),Trial(ix1_t,18)));
    onsets_run14_EV_1 = onsets_run14_EV(find(onsets_run14_EV(:,2)==1),1)';
    onsets_run14_EV_2 = onsets_run14_EV(find(onsets_run14_EV(:,2)==2),1)';
    onsets_run14_EV_4 = onsets_run14_EV(find(onsets_run14_EV(:,2)==4),1)';
    
    % All event onsets for baseline and each monetary reward level
    onsets_base = [onsets_base_EV];
    onsets_EV1 = [onsets_run9_EV_1;onsets_run10_EV_1;onsets_run11_EV_1;onsets_run12_EV_1;onsets_run13_EV_1;onsets_run14_EV_1];
    onsets_EV2 = [onsets_run9_EV_2;onsets_run10_EV_2;onsets_run11_EV_2;onsets_run12_EV_2;onsets_run13_EV_2;onsets_run14_EV_2];
    onsets_EV4 = [onsets_run9_EV_4;onsets_run10_EV_4;onsets_run11_EV_4;onsets_run12_EV_4;onsets_run13_EV_4;onsets_run14_EV_4];   
    
    % save text files for event related onsets
    if subjects(s) < 10
        % onsets events
        fname_BASE = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew3/s00',num2str(subjects(s)),'_EV0_BASE.txt'];
        fname_EV1 = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew3/s00',num2str(subjects(s)),'_EV1.txt'];
        fname_EV2 = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew3/s00',num2str(subjects(s)),'_EV2.txt'];
        fname_EV4 = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew3/s00',num2str(subjects(s)),'_EV4.txt'];
        % onsets event start trial of block
        %fname_EVstart = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related/s0',num2str(subjects(s)),'_EVstart.txt'];         
    else
        % onsets events
        fname_BASE = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew3/s0',num2str(subjects(s)),'_EV0_BASE.txt'];
        fname_EV1 = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew3/s0',num2str(subjects(s)),'_EV1.txt'];
        fname_EV2 = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew3/s0',num2str(subjects(s)),'_EV2.txt'];
        fname_EV4 = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew3/s0',num2str(subjects(s)),'_EV4.txt'];
        % onsets event start trial of block
        %fname_EVstart = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related/s',num2str(subjects(s)),'_EVstart.txt']; 
    end
    
    % writing the onsets for the events (total) and the baseline events
    dlmwrite(fname_BASE, onsets_base, 'delimiter','\t')
    dlmwrite(fname_EV1,onsets_EV1,'delimiter','\t')
    dlmwrite(fname_EV2,onsets_EV2,'delimiter','\t')
    dlmwrite(fname_EV4,onsets_EV4,'delimiter','\t')
    
    
    % event related reward 3 -- SEPARATED BY MONETARY VALUES AND LIQUID TYPE (EV1_JUICE, EV2_JUICE, EV4_JUICE, EV1_NEUT, EV2_NEUT, EV4_NEUT, EV1_SALT, EV2_SALT, EV4_SALT)
    
    % run 8: baseline -- this is the same as the previous one, text is just
    % a placeholder to indicate that this has already been calculated
    
    % TWO JUICE RUNS 
    % get indices for both runs
    ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,2) & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
    ix1_t = find(Trial.subID==subjects(s) & Trial.runID==runkey(s,2) & strcmp(Trial.runType,'incentive'));
    ix2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,3) & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
    ix2_t = find(Trial.subID==subjects(s) & Trial.runID==runkey(s,3) & strcmp(Trial.runType,'incentive'));
    % create tables for both runs
    run1 = num2cell(repmat(runkey(s,2),48,1));
    run2 = num2cell(repmat(runkey(s,3),48,1));
    liquid = cell(48,1);
    liquid(:) = {'juice'};
    table_1 = table(run1,liquid);
    table_2 = table(run2,liquid);
    % in the table, there is trial, onsets, monetary reward, run number, and liquid type
    %[table2array(Tstim(ix1,4)),table2array(Tstim(ix1,7)),table2array(Trial(ix1_t,18)),run1,table_1]
    table_EV_JUICE_run1 = [Tstim(ix1,4),Tstim(ix1,7),Trial(ix1_t,18),table_1];
    table_EV_JUICE_run2 = [Tstim(ix2,4),Tstim(ix2,7),Trial(ix2_t,18),table_2];
    % subset the trials for each monetary level 
    % subject 3, stopped scan halfway through second juice run
    if subjects(s) == 3
        EV1_JUICE_run2 = [table_EV_JUICE_run2.onset_exp(find(table_EV_JUICE_run2.moneyreward==1))',repmat(NaN,1,16-length(table_EV_JUICE_run2.onset_exp(find(table_EV_JUICE_run2.moneyreward==1))))];
        onsets_EV1_JUICE = [table_EV_JUICE_run1.onset_exp(find(table_EV_JUICE_run1.moneyreward==1))';EV1_JUICE_run2];
        EV2_JUICE_run2 = [table_EV_JUICE_run2.onset_exp(find(table_EV_JUICE_run2.moneyreward==2))',repmat(NaN,1,16-length(table_EV_JUICE_run2.onset_exp(find(table_EV_JUICE_run2.moneyreward==2))))];
        onsets_EV2_JUICE = [table_EV_JUICE_run1.onset_exp(find(table_EV_JUICE_run1.moneyreward==2))';EV2_JUICE_run2];
        EV4_JUICE_run2 = [table_EV_JUICE_run2.onset_exp(find(table_EV_JUICE_run2.moneyreward==4))',repmat(NaN,1,16-length(table_EV_JUICE_run2.onset_exp(find(table_EV_JUICE_run2.moneyreward==4))))];
        onsets_EV4_JUICE = [table_EV_JUICE_run1.onset_exp(find(table_EV_JUICE_run1.moneyreward==4))';EV4_JUICE_run2];
    else
        onsets_EV1_JUICE = [table_EV_JUICE_run1.onset_exp(find(table_EV_JUICE_run1.moneyreward==1))';table_EV_JUICE_run2.onset_exp(find(table_EV_JUICE_run2.moneyreward==1))'];
        onsets_EV2_JUICE = [table_EV_JUICE_run1.onset_exp(find(table_EV_JUICE_run1.moneyreward==2))';table_EV_JUICE_run2.onset_exp(find(table_EV_JUICE_run2.moneyreward==2))'];
        onsets_EV4_JUICE = [table_EV_JUICE_run1.onset_exp(find(table_EV_JUICE_run1.moneyreward==4))';table_EV_JUICE_run2.onset_exp(find(table_EV_JUICE_run2.moneyreward==4))'];
    end
    
    % TWO NEUTRAL RUNS
    % get indices for both runs
    ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,4) & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
    ix1_t = find(Trial.subID==subjects(s) & Trial.runID==runkey(s,4) & strcmp(Trial.runType,'incentive'));
    ix2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,5) & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
    ix2_t = find(Trial.subID==subjects(s) & Trial.runID==runkey(s,5) & strcmp(Trial.runType,'incentive'));
    % create tables for both runs
    run1 = num2cell(repmat(runkey(s,4),48,1));
    run2 = num2cell(repmat(runkey(s,5),48,1));
    liquid = cell(48,1);
    liquid(:) = {'neutral'};
    table_1 = table(run1,liquid);
    table_2 = table(run2,liquid);
    % in the table, there is trial, onsets, monetary reward, run number, and liquid type
    %[table2array(Tstim(ix1,4)),table2array(Tstim(ix1,7)),table2array(Trial(ix1_t,18)),run1,table_1]
    table_EV_NEUT_run1 = [Tstim(ix1,4),Tstim(ix1,7),Trial(ix1_t,18),table_1];
    table_EV_NEUT_run2 = [Tstim(ix2,4),Tstim(ix2,7),Trial(ix2_t,18),table_2];
    % subset the trials for each monetary level 
    onsets_EV1_NEUT = [table_EV_NEUT_run1.onset_exp(find(table_EV_NEUT_run1.moneyreward==1))';table_EV_NEUT_run2.onset_exp(find(table_EV_NEUT_run2.moneyreward==1))'];
    onsets_EV2_NEUT = [table_EV_NEUT_run1.onset_exp(find(table_EV_NEUT_run1.moneyreward==2))';table_EV_NEUT_run2.onset_exp(find(table_EV_NEUT_run2.moneyreward==2))'];
    onsets_EV4_NEUT = [table_EV_NEUT_run1.onset_exp(find(table_EV_NEUT_run1.moneyreward==4))';table_EV_NEUT_run2.onset_exp(find(table_EV_NEUT_run2.moneyreward==4))'];
        
    % TWO SALTWATER RUNS
    % get indices for both runs
    ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,6) & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
    ix1_t = find(Trial.subID==subjects(s) & Trial.runID==runkey(s,6) & strcmp(Trial.runType,'incentive'));
    ix2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,7) & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
    ix2_t = find(Trial.subID==subjects(s) & Trial.runID==runkey(s,7) & strcmp(Trial.runType,'incentive'));
    % create tables for both runs
    run1 = num2cell(repmat(runkey(s,6),48,1));
    run2 = num2cell(repmat(runkey(s,7),48,1));
    liquid = cell(48,1);
    liquid(:) = {'salt'};
    table_1 = table(run1,liquid);
    table_2 = table(run2,liquid);
    % in the table, there is trial, onsets, monetary reward, run number, and liquid type
    %[table2array(Tstim(ix1,4)),table2array(Tstim(ix1,7)),table2array(Trial(ix1_t,18)),run1,table_1]
    table_EV_SALT_run1 = [Tstim(ix1,4),Tstim(ix1,7),Trial(ix1_t,18),table_1];
    table_EV_SALT_run2 = [Tstim(ix2,4),Tstim(ix2,7),Trial(ix2_t,18),table_2];
    % subset the trials for each monetary level 
    onsets_EV1_SALT = [table_EV_SALT_run1.onset_exp(find(table_EV_SALT_run1.moneyreward==1))';table_EV_SALT_run2.onset_exp(find(table_EV_SALT_run2.moneyreward==1))'];
    onsets_EV2_SALT = [table_EV_SALT_run1.onset_exp(find(table_EV_SALT_run1.moneyreward==2))';table_EV_SALT_run2.onset_exp(find(table_EV_SALT_run2.moneyreward==2))'];
    onsets_EV4_SALT = [table_EV_SALT_run1.onset_exp(find(table_EV_SALT_run1.moneyreward==4))';table_EV_SALT_run2.onset_exp(find(table_EV_SALT_run2.moneyreward==4))'];   

    % save text files for event related onsets
    if subjects(s) < 10
        % onsets events
        fname_BASE = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s00',num2str(subjects(s)),'_EV0_BASE.txt'];
        fname_EV1_JUICE = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s00',num2str(subjects(s)),'_EV1_JUICE.txt'];
        fname_EV2_JUICE = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s00',num2str(subjects(s)),'_EV2_JUICE.txt'];
        fname_EV4_JUICE = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s00',num2str(subjects(s)),'_EV4_JUICE.txt'];
        fname_EV1_NEUT = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s00',num2str(subjects(s)),'_EV1_NEUT.txt'];
        fname_EV2_NEUT = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s00',num2str(subjects(s)),'_EV2_NEUT.txt'];
        fname_EV4_NEUT = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s00',num2str(subjects(s)),'_EV4_NEUT.txt'];
        fname_EV1_SALT = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s00',num2str(subjects(s)),'_EV1_SALT.txt'];
        fname_EV2_SALT = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s00',num2str(subjects(s)),'_EV2_SALT.txt'];
        fname_EV4_SALT = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s00',num2str(subjects(s)),'_EV4_SALT.txt'];        
        % onsets event start trial of block
        %fname_EVstart = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related/s0',num2str(subjects(s)),'_EVstart.txt'];         
    else
        % onsets events
        fname_BASE = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s0',num2str(subjects(s)),'EV0_BASE.txt'];
        fname_EV1_JUICE = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s0',num2str(subjects(s)),'_EV1_JUICE.txt'];
        fname_EV2_JUICE = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s0',num2str(subjects(s)),'_EV2_JUICE.txt'];
        fname_EV4_JUICE = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s0',num2str(subjects(s)),'_EV4_JUICE.txt'];
        fname_EV1_NEUT = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s0',num2str(subjects(s)),'_EV1_NEUT.txt'];
        fname_EV2_NEUT = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s0',num2str(subjects(s)),'_EV2_NEUT.txt'];
        fname_EV4_NEUT = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s0',num2str(subjects(s)),'_EV4_NEUT.txt'];
        fname_EV1_SALT = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s0',num2str(subjects(s)),'_EV1_SALT.txt'];
        fname_EV2_SALT = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s0',num2str(subjects(s)),'_EV2_SALT.txt'];
        fname_EV4_SALT = ['/Users/debbieyee/Dropbox/CCPLabProjects/LiquidFeedback_FMRI/Data/onsets/event_related_rew9/s0',num2str(subjects(s)),'_EV4_SALT.txt'];                
        % onsets event start trial of block
        %fname_EVstart = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related/s',num2str(subjects(s)),'_EVstart.txt']; 
    end    
    
    
    % writing the onsets for the events (9 total) 
    dlmwrite(fname_BASE, onsets_base, 'delimiter','\t')
    dlmwrite(fname_EV1_JUICE,onsets_EV1_JUICE,'delimiter','\t')
    dlmwrite(fname_EV2_JUICE,onsets_EV2_JUICE,'delimiter','\t')
    dlmwrite(fname_EV4_JUICE,onsets_EV4_JUICE,'delimiter','\t')
    dlmwrite(fname_EV1_NEUT,onsets_EV1_NEUT,'delimiter','\t')
    dlmwrite(fname_EV2_NEUT,onsets_EV2_NEUT,'delimiter','\t')
    dlmwrite(fname_EV4_NEUT,onsets_EV4_NEUT,'delimiter','\t')
    dlmwrite(fname_EV1_SALT,onsets_EV1_SALT,'delimiter','\t')
    dlmwrite(fname_EV2_SALT,onsets_EV2_SALT,'delimiter','\t')
    dlmwrite(fname_EV4_SALT,onsets_EV4_SALT,'delimiter','\t')
    
end

% Text to display at the end of the code
disp('Completed creating stimuli onsets and durations for duration modulated block and event-related analyses for all subjects, and saved to dropbox folder on computer.');    
    

%% Extracting the event onsets for block & event-related designs: Subjects 17-51
subjects = [2:4 6:17];

% Runkey of the liquid types based on the behavioral checklist.
% NOTE: the runs start at 8, not 1.
%[base1 base2 juice juice neutral neutral saltwater saltwater]
runkey = [8 9 10 13 14 11 12;    % s02
          8 11 12 9 10 13 14;    % s03
          8 13 14 9 10 11 12;    % s04
          8 13 14 11 12 9 10;    % s06
          8 9 10 11 12 13 14;    % s07
          8 9 10 13 14 11 12;    % s08
          8 11 12 9 10 13 14;    % s09
          8 13 14 9 10 11 12;    % s10
          8 11 12 13 14 9 10;    % s11
          8 13 14 11 12 9 10;    % s12
          8 9 10 11 12 13 14;    % s13
          8 9 10 13 14 11 12;    % s14
          8 11 12 9 10 13 14;    % s15
          8 13 14 9 10 11 12;    % s16
          8 11 12 13 14 9 10];   % s17
      
% extract timing onsets for each run, for each subject   

subjects = [2:4 6:17];

          8 11 12 13 14 9 10;    % s18
          8 13 14 11 12 9 10;    % s19
          8 9 10 11 12 13 14;    % s20
          8 9 10 13 14 11 12;    % s21
          8 11 12 9 10 13 14;    % s23 SKIPPED SUBJECT 22
          8 13 14 9 10 11 12;    % s24
          8 11 12 13 14 9 10;    % s25 






%     
%     % run 2 & 3: juice onsets (2 runs)
%     ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,2) & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
%     ix1_t=find(Trial.subID==subjects(s) & Trial.runID==runkey(s,2) & strcmp(Trial.runType,'incentive'));
%     onsets_juice1_EV = table2array(horzcat(Tstim(ix1,7),Trial(ix1_t,18)));
%     onsets_juice1_EV_1 = onsets_juice1_EV(find(onsets_juice1_EV(:,2)==1),1)';
%     onsets_juice1_EV_2 = onsets_juice1_EV(find(onsets_juice1_EV(:,2)==2),1)';
%     onsets_juice1_EV_4 = onsets_juice1_EV(find(onsets_juice1_EV(:,2)==4),1)';
%     
%     ix2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,3) & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));   
%     ix2_t=find(Trial.subID==subjects(s) & Trial.runID==runkey(s,3) & strcmp(Trial.runType,'incentive'));    
%     onsets_juice2_EV = table2array(horzcat(Tstim(ix2,7),Trial(ix2_t,18)));
%     onsets_juice2_EV_1 = onsets_juice2_EV(find(onsets_juice2_EV(:,2)==1),1)';
%     onsets_juice2_EV_2 = onsets_juice2_EV(find(onsets_juice2_EV(:,2)==2),1)';
%     onsets_juice2_EV_4 = onsets_juice2_EV(find(onsets_juice2_EV(:,2)==4),1)'; 
%     if subjects(s)==3
%         onsets_juice2_EV_1 = [onsets_juice2_EV_1,repmat(NaN,1,16-length(onsets_juice2_EV_1))];
%         onsets_juice2_EV_2 = [onsets_juice2_EV_2,repmat(NaN,1,16-length(onsets_juice2_EV_2))];
%         onsets_juice2_EV_4 = [onsets_juice2_EV_4,repmat(NaN,1,16-length(onsets_juice2_EV_4))];
%     end
%     
%     % run 4 & 5: neutral onsets (2 runs):
%     ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,4) & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
%     ix1_t=find(Trial.subID==subjects(s) & Trial.runID==runkey(s,4) & strcmp(Trial.runType,'incentive'));
%     onsets_neut1_EV = table2array(horzcat(Tstim(ix1,7),Trial(ix1_t,18)));
%     onsets_neut1_EV_1 = onsets_neut1_EV(find(onsets_neut1_EV(:,2)==1),1)';
%     onsets_neut1_EV_2 = onsets_neut1_EV(find(onsets_neut1_EV(:,2)==2),1)';
%     onsets_neut1_EV_4 = onsets_neut1_EV(find(onsets_neut1_EV(:,2)==4),1)';    
%     
%     ix2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,5) & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));  
%     ix2_t=find(Trial.subID==subjects(s) & Trial.runID==runkey(s,5) & strcmp(Trial.runType,'incentive'));
%     onsets_neut2_EV = table2array(horzcat(Tstim(ix2,7),Trial(ix2_t,18)));
%     onsets_neut2_EV_1 = onsets_neut2_EV(find(onsets_neut2_EV(:,2)==1),1)';
%     onsets_neut2_EV_2 = onsets_neut2_EV(find(onsets_neut2_EV(:,2)==2),1)';
%     onsets_neut2_EV_4 = onsets_neut2_EV(find(onsets_neut2_EV(:,2)==4),1)';       
%     
%     % run 6 & 7: saltwater onsets (2 runs)
%     ix1 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,6) & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
%     ix1_t=find(Trial.subID==subjects(s) & Trial.runID==runkey(s,6) & strcmp(Trial.runType,'incentive'));
%     onsets_salt1_EV = table2array(horzcat(Tstim(ix1,7),Trial(ix1_t,18)));
%     onsets_salt1_EV_1 = onsets_salt1_EV(find(onsets_salt1_EV(:,2)==1),1)';
%     onsets_salt1_EV_2 = onsets_salt1_EV(find(onsets_salt1_EV(:,2)==2),1)';
%     onsets_salt1_EV_4 = onsets_salt1_EV(find(onsets_salt1_EV(:,2)==4),1)';   
%     
%     ix2 = find(Tstim.subID==subjects(s) & Tstim.runID==runkey(s,7) & strcmp(Tstim.runType,'incentive') & strcmp(Tstim.stim_present,'trialstart'));
%     ix2_t=find(Trial.subID==subjects(s) & Trial.runID==runkey(s,7) & strcmp(Trial.runType,'incentive'));
%     onsets_salt2_EV = table2array(horzcat(Tstim(ix2,7),Trial(ix2_t,18)));
%     onsets_salt2_EV_1 = onsets_salt2_EV(find(onsets_salt2_EV(:,2)==1),1)';
%     onsets_salt2_EV_2 = onsets_salt2_EV(find(onsets_salt2_EV(:,2)==2),1)';
%     onsets_salt2_EV_4 = onsets_salt2_EV(find(onsets_salt2_EV(:,2)==4),1)';  
%  
%     % All event onsets for each monetary reward level
%     %onsets_EV1 = [onsets_base_EV_1;onsets_juice1_EV_1;onsets_juice2_EV_1;onsets_neut1_EV_1;onsets_neut2_EV_1;onsets_salt1_EV_1;onsets_salt2_EV_1];
%     %onsets_EV2 = [onsets_base_EV_2;onsets_juice1_EV_2;onsets_juice2_EV_2;onsets_neut1_EV_2;onsets_neut2_EV_2;onsets_salt1_EV_2;onsets_salt2_EV_2];
%     %onsets_EV4 = [onsets_base_EV_4;onsets_juice1_EV_4;onsets_juice2_EV_4;onsets_neut1_EV_4;onsets_neut2_EV_4;onsets_salt1_EV_4;onsets_salt2_EV_4];
%     
%     onsets_EV1 = [onsets_juice1_EV_1;onsets_juice2_EV_1;onsets_neut1_EV_1;onsets_neut2_EV_1;onsets_salt1_EV_1;onsets_salt2_EV_1];
%     onsets_EV2 = [onsets_juice1_EV_2;onsets_juice2_EV_2;onsets_neut1_EV_2;onsets_neut2_EV_2;onsets_salt1_EV_2;onsets_salt2_EV_2];
%     onsets_EV4 = [onsets_juice1_EV_4;onsets_juice2_EV_4;onsets_neut1_EV_4;onsets_neut2_EV_4;onsets_salt1_EV_4;onsets_salt2_EV_4];
%     
%     
%     % Event onsets only at first of block
%     %onsets_EVstart = [onsets_base;onsets_juice;onsets_neut;onsets_salt];
%     
%     % save text files for event related onsets
%     if subjects(s) < 10
%         % onsets events
%         fname_EV1 = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related_rew/s0',num2str(subjects(s)),'_EV1.txt'];
%         fname_EV2 = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related_rew/s0',num2str(subjects(s)),'_EV2.txt'];
%         fname_EV4 = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related_rew/s0',num2str(subjects(s)),'_EV4.txt'];
%         % onsets event start trial of block
%         %fname_EVstart = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related/s0',num2str(subjects(s)),'_EVstart.txt'];
%              
%     else
%         % onsets events
%         fname_EV1 = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related_rew/s',num2str(subjects(s)),'_EV1.txt'];
%         fname_EV2 = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related_rew/s',num2str(subjects(s)),'_EV2.txt'];
%         fname_EV4 = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related_rew/s',num2str(subjects(s)),'_EV4.txt'];
%         % onsets event start trial of block
%         %fname_EVstart = ['/Users/debbieyee/Documents/Projects/LiquidFeedback_FMRI/Data/onsets/event_related/s',num2str(subjects(s)),'_EVstart.txt']; 
%     end
%     
%     % writing the onsets for the events and the start of block events
%     dlmwrite(fname_EV1,onsets_EV1,'delimiter','\t')
%     dlmwrite(fname_EV2,onsets_EV2,'delimiter','\t')
%     dlmwrite(fname_EV4,onsets_EV4,'delimiter','\t')
%     %dlmwrite(fname_EVstart,onsets_EVstart,'delimiter','\t')
    
    


%% Mixed Block Design





end

